### ISSUE TITLE
cleared cart item while logout(request)

### ISSUE THREAD

**Issue by armsmani** [lazybird/django-carton#18]
i have added item in basket after that i have logout using "logout(request)" then cart will clear all item. Because logout(request) will clear all session. How can i overcome this situation.

**Comment by lazybird** [comment]
I'm closing this issue. Let's reopen if this is still a discussion point.

**Comment by umar13893** [comment]
I also have the same issue I added this code in my logout view function It will delete all sessions except this cart session. 

`def user_logout(request):

    try:
        for key in list(request.session.keys()):
            if key == 'CART':
                continue
            del request.session[key]
    except KeyError:
        pass
    return HttpResponseRedirect(reversed('userprofile_app:login'))`

request.session.keys() displays all session keys Its works fine in Python3 and Django 1.11
