### ISSUE TITLE
Key Error on Django 1.7

### ISSUE THREAD

**Issue by briem-bixly** [lazybird/django-carton#20]
When running your example shopping cart app in Django 1.7, a KeyError is thrown in {% get_cart as cart %}.

'request' at line 22 in get_cart

**Comment by lazybird** [comment]
Hi and thanks for the comment.
I'm wondering if this as something to do with a missing `request` object in the template context. May be this is related to  the [context processors setting](https://docs.djangoproject.com/en/1.7/ref/settings/#std:setting-TEMPLATE_CONTEXT_PROCESSORS).

I'd like to know if you find a solution and see if there is something we should document or modify in django-carton.

Thanks.

**Comment by briem-bixly** [comment]
The way I got around this was adding a custom context processor that returns the request.

like so: 
TEMPLATE_CONTEXT_PROCESSORS = (
    "django.contrib.auth.context_processors.auth",
    "django.core.context_processors.debug",
    "django.core.context_processors.i18n",
    "django.core.context_processors.media",
    "django.core.context_processors.static",
    "django.core.context_processors.tz",
    "django.contrib.messages.context_processors.messages",
    "saas.context_processors.get_request"
)
def get_request(request):
    return {'request': request}

**Comment by pedrovazsa** [comment]
Adding `django.core.context_processors.request`also worked for me (which is pretty much the same method as @briem-bixly's).

**Comment by jlward** [comment]
Thanks @pedrovazsa for the workaround. :)
